version: "3.6"

services:
  app:
    build: ./
    container_name: travel
    volumes:
      - ./:/app
      - H:\ApiResources\TravelApp:/res
    ports:
      - 8080:8080
    expose:
      - 8080
    links:
      - "database:database"
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ktor
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    expose:
      - 5432

